# License: MIT
# Copyright © 2022 Frequenz Energy-as-a-Service GmbH

"""
Handling of timeseries streams.

A timeseries is a stream (normally an async iterator) of
[`Sample`][frequenz.sdk.timeseries.Sample]s.

Timeseries can be consumed from
[`Source`][frequenz.sdk.timeseries.Source]s and new timeseries can be
generated by sending samples to
a [`Sink`][frequenz.sdk.timeseries.Sink]
"""

from ._base_types import Sample, Sink, Source
from ._resampler import GroupResampler, Resampler, ResamplingFunction

__all__ = [
    "GroupResampler",
    "Resampler",
    "ResamplingFunction",
    "Sample",
    "Sink",
    "Source",
]
